pan_controller:
  controller:
    package: dynamixel_controllers
    module: joint_position_controller
    type: JointPositionController
  joint_name: pan
  joint_speed: 1.0
  motor:
    id: 1
    init: 0
    min: 0
    max: 512

tilt_controller:
  controller:
    package: dynamixel_controllers
    module: joint_position_controller
    type: JointPositionController
  joint_name: tilt
  joint_speed: 1.0
  motor:
    id: 2
    init: 0
    min: 0
    max: 512
